# Generated by Django 3.0.6 on 2020-07-30 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ingredients', models.CharField(max_length=200)),
                ('label', models.CharField(max_length=100)),
                ('packaging', models.CharField(max_length=100)),
                ('saturedFat', models.CharField(max_length=100)),
                ('fat', models.CharField(max_length=100)),
                ('salt', models.CharField(max_length=100)),
                ('sugar', models.CharField(max_length=100)),
                ('allergen', models.CharField(max_length=100)),
                ('nutriscore', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('pictureUrl', models.URLField()),
                ('category', models.ManyToManyField(related_name='category', to='pages.Category')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailAdress', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('favorites', models.ManyToManyField(related_name='product', to='pages.Product')),
            ],
        ),
    ]
